import "server-only";

/**
 * Typed thin wrappers around Supabase RPC calls.
 *
 * Why this module exists
 * ----------------------
 * supabase-js 2.105 has strict generic inference on `.rpc(fn, args)` that
 * only flows cleanly when the full Database type is generated by the
 * Supabase CLI. Hand-maintained Function entries in `types.ts` cause the
 * generic to narrow `Args` to `never`, which makes every call site
 * either fail to compile or require an `as never` cast.
 *
 * Rather than battle the library generics across every caller, we keep
 * `Database['public']['Functions']` minimal and centralise the cast
 * here. Each wrapper:
 *
 *   1. Types its own Args at the call boundary.
 *   2. Performs ONE narrow `unknown`-cast against the returned rows.
 *   3. Returns a strongly-typed row array.
 *
 * Net effect: call sites see full type safety on both arguments and
 * response data, with zero `any` leakage.
 */

import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

type AnyClient = SupabaseClient<Database>;

/**
 * Escape hatch for the single line where we talk to an untyped RPC
 * surface. Everything downstream of this cast is fully typed.
 */
function untypedRpc(client: AnyClient) {
  return client.rpc as unknown as (
    fn: string,
    args?: Record<string, unknown>,
  ) => Promise<{ data: unknown; error: { message: string } | null }>;
}

// --- client_revenue_summary -------------------------------------------------

export interface ClientRevenueSummaryRow {
  client_id: string;
  total_paid: number;
  invoice_count: number;
}

export async function rpcClientRevenueSummary(
  client: AnyClient,
  args: { p_limit: number },
): Promise<ClientRevenueSummaryRow[]> {
  const { data } = await untypedRpc(client)("client_revenue_summary", args);
  return (Array.isArray(data) ? data : []) as ClientRevenueSummaryRow[];
}

// --- invoice_status_summary -------------------------------------------------

export interface InvoiceStatusSummaryRow {
  invoice_count: number;
  total_amount: number;
}

export async function rpcInvoiceStatusSummary(
  client: AnyClient,
  args: { p_status: string },
): Promise<InvoiceStatusSummaryRow[]> {
  const { data } = await untypedRpc(client)("invoice_status_summary", args);
  return (Array.isArray(data) ? data : []) as InvoiceStatusSummaryRow[];
}

// --- client_invoice_metrics -------------------------------------------------

export interface ClientInvoiceMetricsRow {
  invoice_count: number;
  paid_total: number;
}

export async function rpcClientInvoiceMetrics(
  client: AnyClient,
  args: { p_client_id: string },
): Promise<ClientInvoiceMetricsRow[]> {
  const { data } = await untypedRpc(client)("client_invoice_metrics", args);
  return (Array.isArray(data) ? data : []) as ClientInvoiceMetricsRow[];
}
