-- =============================================================================
-- 0021_admin_exports.sql
--
-- Phase-4 hardening: tamper-evident audit archive + DPDP user-data
-- export, both backed by Supabase Storage buckets.
--
-- Buckets:
--   1. admin-exports  — hourly JSONL snapshots of admin_actions, written
--                        by the `/api/cron/admin-export` route. Append-
--                        only by convention (one new file per hour).
--   2. user-exports   — per-user JSON dumps generated by the founder
--                        console `user.data_export` action for DPDP
--                        compliance.
--
-- Both buckets are PRIVATE and have NO authenticated RLS policy. They
-- are read/written exclusively via the service-role client through the
-- admin code paths.
-- =============================================================================

insert into storage.buckets (id, name, public)
values
  ('admin-exports', 'admin-exports', false),
  ('user-exports',  'user-exports',  false)
on conflict (id) do nothing;

-- No authenticated SELECT / INSERT / UPDATE / DELETE policies on either
-- bucket. The default storage.objects RLS is enabled (Supabase enables
-- it on every bucket); the absence of policies means only the
-- service-role bypass can touch these objects, which is exactly what
-- we want.
--
-- Note: we intentionally do NOT `COMMENT ON TABLE storage.buckets` —
-- that table is owned by `supabase_storage_admin`, and the SQL editor
-- runs as `postgres` which lacks ownership. The bucket INSERT above
-- is the only statement Supabase exposes to non-owners.
